FROM node:20
WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm ci

# Копируем всё содержимое code/ в /app
COPY . .

EXPOSE 8080
ENV NODE_ENV=production

RUN make build

CMD ["make", "start"]